# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a38823b047eefdfaedd3ecfb254c9a0c91beb1e10bea148513d18748a808ffc12bc0d978a876ada10246787e3a632e34c45fe5dbc8ec18557909c2cd17df9a9

test:
  secret_key_base: 0408623a7f1535f83d7eefc8f6bba08281da7451cd1fe88efff17a30c96673680fc5c18acacaf4590400de04a4b1919a0ac8d051b44643c438fa1dab4b65c1c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
